url: https://thimlohse.github.io
baseurl: /portfolio_template/


# Site settings
title: Thim Lohse
email: lohse@kth.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Thim Lohse
  pic: 2
  position: Analyst Consultant
  social:
    - title: facebook
      url: https://www.facebook.com/thim.lohse
    - title: github
      url: https://github.com/ThimLohse
    - title: linkedin
      url: https://www.linkedin.com/in/thimlohse
    - title: envelope
      url: mailto:lohse@kth.se

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/thim.lohse
  - title: github
    url: https://github.com/ThimLohse
  - title: linkedin
    url: https://www.linkedin.com/in/thimlohse

# Postal address (add as many lines as necessary)
address:
  - line: Eliegatan 11
  - line: 172 73
  - line: Sundbyberg, Stockholm

# Build settings
markdown: kramdown
permalink: pretty
remote-theme: y7kim/agency-jekyll-theme
